2023/05/24 12:45:53 INFO  : Backup_Scripts/output.slurm: Updated modification time in destination
2023/05/24 12:45:54 INFO  : Backup_Scripts/Box_Backup.slurm: Copied (replaced existing)
2023/05/24 12:45:54 INFO  : Backup_Scripts/backup_log.txt: Copied (replaced existing)
2023/05/24 12:46:07 NOTICE: krauss_group/SWCNT_Stark_Effect/65_Pristine_Long/TDDFT_QCHEM/.logger: Can't transfer non file/directory
